import {buildStep} from "./domain/Step";

export default class StepsRepository {
    dogoxoSteps;
    kittyFurSteps;
    petslySteps;

    constructor() {
        this.dogoxoSteps = [
            buildStep(1, "Pull master", "echo Lorem ipsum dolor sit amet, consectetur adipiscing elit && powershell.exe Start-Sleep -seconds 1 && echo Sed elit quam, volutpat at egestas eu, efficitur nec nisi. Etiam euismod eget magna ac sagittis. Phasellus tempus tortor vel nulla sodales, in vestibulum nulla tristique. Etiam eleifend scelerisque diam. && powershell.exe Start-Sleep -seconds 1 && echo Sed eu urna luctus arcu egestas vestibulum eu quis enim. Pellentesque eget iaculis mi, ut efficitur lectus. Nunc ipsum mauris, viverra non mauris id, vestibulum faucibus velit && powershell.exe Start-Sleep -seconds 1"),
            buildStep(2, "npm install", "echo Proin varius, erat et pulvinar consequat, turpis mauris dapibus risus, id faucibus arcu odio at ante. Cras sagittis vestibulum odio, ac condimentum velit commodo sed. && powershell.exe Start-Sleep -seconds 1 && echo Vivamus vitae nibh sed ante ultricies euismod a a lorem. Nam commodo, nulla non placerat faucibus, tellus ante egestas leo, vel dignissim ex augue et sapien. && powershell.exe Start-Sleep -seconds 1 && echo Pellentesque quam est, dictum in tellus in, maximus malesuada arcu. Vestibulum eu libero sed metus vehicula gravida. Fusce non tellus orci. && powershell.exe Start-Sleep -seconds 1"),
            buildStep(3, "Demo error", "Some invalid command"),
            buildStep(4, "Rebuild & run backend", "echo Quisque lobortis nisl at orci pellentesque, ut consectetur est consequat. Mauris elit justo, molestie ut venenatis quis, tempor vel lacus. Aenean id purus in risus ornare gravida a ac velit. Duis egestas rhoncus nulla id vestibulum. Cras quis tortor at dui consequat commodo non non est. Morbi mollis quam a dolor tempor commodo. Ut hendrerit sollicitudin lorem vel viverra. Pellentesque varius aliquam vulputate. Nullam feugiat semper nisl, eget auctor mi faucibus ac. Proin diam sem, pharetra id quam et, ultricies commodo libero. Nunc maximus faucibus mi eget sollicitudin. && powershell.exe Start-Sleep -seconds 1 && echo Pellentesque at laoreet nibh, non volutpat est. Curabitur vitae efficitur tortor. Nulla congue fermentum nunc, sed pulvinar eros bibendum eu. Vivamus faucibus id arcu vitae pellentesque. Donec eget elit sed odio pulvinar scelerisque. In et tortor at augue placerat pulvinar. && powershell.exe Start-Sleep -seconds 3 && echo Suspendisse imperdiet ullamcorper nibh, in faucibus justo suscipit sit amet. && powershell.exe Start-Sleep -seconds 1 && echo Nullam efficitur convallis turpis et vehicula. Ut ac leo fringilla, condimentum ipsum sit amet, convallis erat. Ut elementum orci elit, ut iaculis libero vestibulum in. In elementum ligula eros, a efficitur sem dignissim in && powershell.exe Start-Sleep -seconds 2")
        ];

        this.kittyFurSteps = [
            buildStep(1, "Start Docker", "echo Lorem ipsum dolor sit amet, consectetur adipiscing elit && powershell.exe Start-Sleep -seconds 1 && echo Sed elit quam, volutpat at egestas eu, efficitur nec nisi. Etiam euismod eget magna ac sagittis. Phasellus tempus tortor vel nulla sodales, in vestibulum nulla tristique. Etiam eleifend scelerisque diam. && powershell.exe Start-Sleep -seconds 1 && echo Sed eu urna luctus arcu egestas vestibulum eu quis enim. Pellentesque eget iaculis mi, ut efficitur lectus. Nunc ipsum mauris, viverra non mauris id, vestibulum faucibus velit && powershell.exe Start-Sleep -seconds 1"),
            buildStep(2, "Docker compose up", "echo Proin varius, erat et pulvinar consequat, turpis mauris dapibus risus, id faucibus arcu odio at ante. Cras sagittis vestibulum odio, ac condimentum velit commodo sed. && powershell.exe Start-Sleep -seconds 1 && echo Vivamus vitae nibh sed ante ultricies euismod a a lorem. Nam commodo, nulla non placerat faucibus, tellus ante egestas leo, vel dignissim ex augue et sapien. && powershell.exe Start-Sleep -seconds 1 && echo Pellentesque quam est, dictum in tellus in, maximus malesuada arcu. Vestibulum eu libero sed metus vehicula gravida. Fusce non tellus orci. && powershell.exe Start-Sleep -seconds 1"),
            buildStep(4, "Run API", "echo Quisque lobortis nisl at orci pellentesque, ut consectetur est consequat. Mauris elit justo, molestie ut venenatis quis, tempor vel lacus. Aenean id purus in risus ornare gravida a ac velit. Duis egestas rhoncus nulla id vestibulum. Cras quis tortor at dui consequat commodo non non est. Morbi mollis quam a dolor tempor commodo. Ut hendrerit sollicitudin lorem vel viverra. Pellentesque varius aliquam vulputate. Nullam feugiat semper nisl, eget auctor mi faucibus ac. Proin diam sem, pharetra id quam et, ultricies commodo libero. Nunc maximus faucibus mi eget sollicitudin. && powershell.exe Start-Sleep -seconds 1 && echo Pellentesque at laoreet nibh, non volutpat est. Curabitur vitae efficitur tortor. Nulla congue fermentum nunc, sed pulvinar eros bibendum eu. Vivamus faucibus id arcu vitae pellentesque. Donec eget elit sed odio pulvinar scelerisque. In et tortor at augue placerat pulvinar. && powershell.exe Start-Sleep -seconds 3 && echo Suspendisse imperdiet ullamcorper nibh, in faucibus justo suscipit sit amet. && powershell.exe Start-Sleep -seconds 1 && echo Nullam efficitur convallis turpis et vehicula. Ut ac leo fringilla, condimentum ipsum sit amet, convallis erat. Ut elementum orci elit, ut iaculis libero vestibulum in. In elementum ligula eros, a efficitur sem dignissim in && powershell.exe Start-Sleep -seconds 2")
        ];

        this.petslySteps = [
            buildStep(1, "Start Redis", "echo Lorem ipsum dolor sit amet, consectetur adipiscing elit && powershell.exe Start-Sleep -seconds 1 && echo Sed elit quam, volutpat at egestas eu, efficitur nec nisi. Etiam euismod eget magna ac sagittis. Phasellus tempus tortor vel nulla sodales, in vestibulum nulla tristique. Etiam eleifend scelerisque diam. && powershell.exe Start-Sleep -seconds 1 && echo Sed eu urna luctus arcu egestas vestibulum eu quis enim. Pellentesque eget iaculis mi, ut efficitur lectus. Nunc ipsum mauris, viverra non mauris id, vestibulum faucibus velit && powershell.exe Start-Sleep -seconds 1"),
            buildStep(2, "Start Elasticsearch", "echo Proin varius, erat et pulvinar consequat, turpis mauris dapibus risus, id faucibus arcu odio at ante. Cras sagittis vestibulum odio, ac condimentum velit commodo sed. && powershell.exe Start-Sleep -seconds 1 && echo Vivamus vitae nibh sed ante ultricies euismod a a lorem. Nam commodo, nulla non placerat faucibus, tellus ante egestas leo, vel dignissim ex augue et sapien. && powershell.exe Start-Sleep -seconds 1 && echo Pellentesque quam est, dictum in tellus in, maximus malesuada arcu. Vestibulum eu libero sed metus vehicula gravida. Fusce non tellus orci. && powershell.exe Start-Sleep -seconds 1"),
            buildStep(3, "Start SQL Server", "echo Pellentesque malesuada faucibus felis. Integer molestie ornare turpis et aliquet. Praesent sed dui tristique orci accumsan mattis non ac tortor. In hac habitasse platea dictumst. Integer imperdiet faucibus urna, sed suscipit diam lacinia vel. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. && powershell.exe Start-Sleep -seconds 1 && echo Nulla molestie sapien in gravida consequat. && echo Cras laoreet tellus ac accumsan ornare. && powershell.exe Start-Sleep -seconds 1 && echo Proin quis lorem gravida, dignissim metus id, blandit risus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.&& powershell.exe Start-Sleep -seconds 1"),
            buildStep(4, "Deploy backend to IIS", "echo Quisque lobortis nisl at orci pellentesque, ut consectetur est consequat. Mauris elit justo, molestie ut venenatis quis, tempor vel lacus. Aenean id purus in risus ornare gravida a ac velit. Duis egestas rhoncus nulla id vestibulum. Cras quis tortor at dui consequat commodo non non est. Morbi mollis quam a dolor tempor commodo. Ut hendrerit sollicitudin lorem vel viverra. Pellentesque varius aliquam vulputate. Nullam feugiat semper nisl, eget auctor mi faucibus ac. Proin diam sem, pharetra id quam et, ultricies commodo libero. Nunc maximus faucibus mi eget sollicitudin. && powershell.exe Start-Sleep -seconds 1 && echo Pellentesque at laoreet nibh, non volutpat est. Curabitur vitae efficitur tortor. Nulla congue fermentum nunc, sed pulvinar eros bibendum eu. Vivamus faucibus id arcu vitae pellentesque. Donec eget elit sed odio pulvinar scelerisque. In et tortor at augue placerat pulvinar. && powershell.exe Start-Sleep -seconds 3 && echo Suspendisse imperdiet ullamcorper nibh, in faucibus justo suscipit sit amet. && powershell.exe Start-Sleep -seconds 1 && echo Nullam efficitur convallis turpis et vehicula. Ut ac leo fringilla, condimentum ipsum sit amet, convallis erat. Ut elementum orci elit, ut iaculis libero vestibulum in. In elementum ligula eros, a efficitur sem dignissim in && powershell.exe Start-Sleep -seconds 2")
        ];
    }
}